### ISSUE TITLE
Supported fixtures and errors for a "connect expired" Skoda Karoq

### ISSUE THREAD

**Issue by deltamelter** [skodaconnect/myskoda#125]
Recently re-activated the newer version of the android app.
The myskoda[cli] shows a couple of extra bits of information, but interested in what I can find out after resolving the errors and maybe some of the UNKNOWNs.  Does the engine need to be running or the infotainment connected to internet via my phone to connect properly or for more KNOWNs?  I know it has a built in SIM that is no longer licensed except for emergency use.

btw, the error traces leaked the VIN which I have anonymized

[karoq21.yaml.txt](https://github.com/user-attachments/files/17492602/karoq21.yaml.txt)

**Comment by dvx76** [comment]
Thanks for this! We'll take a look as soon as we can. The leaked VINs should be fixed by #119

**Comment by WebSpider** [comment]
Thanks for this! We now can test if our integration keeps on working if you add a car with expired licenses :partying_face:
