### ISSUE TITLE
Initializing: Failed to serialize data

### ISSUE THREAD

**Issue by Partovic** [skodaconnect/myskoda#128]
Hi, had to re-add my enyaq today. Before that, everything was working perfectly. Now it’s not. I don’t know which setting „battery_support“ reflects in the car. So I have no option to workaround this issue. Here’s the error:

`Failed to deserialize data: {"isVehicleInSavedLocation":false,"status":{"chargingRateInKilometersPerHour":0.0,"chargePowerInKw":0.0,"remainingTimeToFullyChargedInMinutes":0,"state":"CONNECT_CABLE","battery":{"remainingCruisingRangeInMeters":282000,"stateOfChargeInPercent":51}},"settings":{"targetStateOfChargeInPercent":100,"preferredChargeMode":"MANUAL","availableChargeModes":["MANUAL"],"chargingCareMode":"DEACTIVATED","autoUnlockPlugWhenCharged":"OFF","maxChargeCurrentAc":"MAXIMUM","batterySupport":"NOT_ALLOWED"},"carCapturedTimestamp":"2024-10-25T21:28:00Z","errors":[]}`

`Traceback (most recent call last):
  File "<string>", line 30, in __mashumaro_from_dict_json__
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'NOT_ALLOWED' is not a valid EnabledState

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 17, in __mashumaro_from_json__
  File "<string>", line 32, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "battery_support" of type Optional[EnabledState] in Settings has invalid value 'NOT_ALLOWED'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 19, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "settings" of type Settings in Charging has invalid value {'targetStateOfChargeInPercent': 100, 'preferredChargeMode': 'MANUAL', 'availableChargeModes': ['MANUAL'], 'chargingCareMode': 'DEACTIVATED', 'autoUnlockPlugWhenCharged': 'OFF', 'maxChargeCurrentAc': 'MAXIMUM', 'batterySupport': 'NOT_ALLOWED'} `

**Comment by WebSpider** [comment]
Thanks for your report! Your car probably is reporting something we havent seen yet. We'll investigate and update the integration as needed
