### ISSUE TITLE
Superb iV: some statistics to take into account

### ISSUE THREAD

**Issue by fursov** [skodaconnect/myskoda#179]
Hi,

I decided to collect some mqtt communication logs from the application. Here I put some filtered content (basically what mqtt_message.py script prints) for SUBSCRIBE messages:

```
[SUBSCRIBE] sent topic filters: '', 'bee240-dd09-4d56-8d8b-fbdfxxxxxxxxx/TMBAZZZZZZZZZZZZZ/account-event/privacy'
[SUBSCRIBE] sent topic filters: '', 'bee240-dd09-4d56-8d8b-fbdfxxxxxxxxx/TMBAZZZZZZZZZZZZZ/operation-request/air-conditioning/set-target-temperature'
[SUBSCRIBE] sent topic filters: '', 'bee240-dd09-4d56-8d8b-fbdfxxxxxxxxx/TMBAZZZZZZZZZZZZZ/operation-request/air-conditioning/start-stop-air-conditioning'
[SUBSCRIBE] sent topic filters: '', 'bee240-dd09-4d56-8d8b-fbdfxxxxxxxxx/TMBAZZZZZZZZZZZZZ/operation-request/auxiliary-heating/start-stop-auxiliary-heating'
[SUBSCRIBE] sent topic filters: '', 'bee240-dd09-4d56-8d8b-fbdfxxxxxxxxx/TMBAZZZZZZZZZZZZZ/operation-request/charging/start-stop-charging'
[SUBSCRIBE] sent topic filters: '', 'bee240-dd09-4d56-8d8b-fbdfxxxxxxxxx/TMBAZZZZZZZZZZZZZ/operation-request/charging/update-battery-support'
[SUBSCRIBE] sent topic filters: '', 'bee240-dd09-4d56-8d8b-fbdfxxxxxxxxx/TMBAZZZZZZZZZZZZZ/operation-request/vehicle-access/honk-and-flash'
[SUBSCRIBE] sent topic filters: '', 'bee240-dd09-4d56-8d8b-fbdfxxxxxxxxx/TMBAZZZZZZZZZZZZZ/operation-request/vehicle-access/lock-vehicle'
[SUBSCRIBE] sent topic filters: '', 'bee240-dd09-4d56-8d8b-fbdfxxxxxxxxx/TMBAZZZZZZZZZZZZZ/operation-request/vehicle-services-backup/apply-backup'
[SUBSCRIBE] sent topic filters: '', 'bee240-dd09-4d56-8d8b-fbdfxxxxxxxxx/TMBAZZZZZZZZZZZZZ/operation-request/vehicle-wakeup/wakeup'
[SUBSCRIBE] sent topic filters: '', 'bee240-dd09-4d56-8d8b-fbdfxxxxxxxxx/TMBAZZZZZZZZZZZZZ/service-event/air-conditioning'
[SUBSCRIBE] sent topic filters: '', 'bee240-dd09-4d56-8d8b-fbdfxxxxxxxxx/TMBAZZZZZZZZZZZZZ/service-event/charging'
[SUBSCRIBE] sent topic filters: '', 'bee240-dd09-4d56-8d8b-fbdfxxxxxxxxx/TMBAZZZZZZZZZZZZZ/service-event/departure'
[SUBSCRIBE] sent topic filters: '', 'bee240-dd09-4d56-8d8b-fbdfxxxxxxxxx/TMBAZZZZZZZZZZZZZ/service-event/vehicle-status/access'
[SUBSCRIBE] sent topic filters: '', 'bee240-dd09-4d56-8d8b-fbdfxxxxxxxxx/TMBAZZZZZZZZZZZZZ/service-event/vehicle-status/lights'
```

There are two differences to what library sends (besides that a lot of messages are missing for Superb iV):
- message `start-stop-auxiliary-heating` is done for `auxiliary-heating` operation, the library does it for `air-conditioning`
- there is no `service-event/departure` request in the library

Please, let me know if more data is needed, I can also send/attach full logs from my mitmproxy run.

**Comment by prvakt** [comment]
actually I can see the difference - our lib is subscribed to **"air-conditioning/start-stop-auxiliary-heating"** but probably it should be **"auxiliary-heating/start-stop-auxiliary-heating"**. I will test it tomorrow

**Comment by prvakt** [comment]
@fursov thanks for your findings. I have somehow missed the auxiliary-heating endpoint when analyzing my logs from mitmproxy. Tested it today and finally I'm receiving state updates in MQTT when auxiliary-heater is started or stopped. I have also added service-event/departure endpoint to the library but that one is not used by any function yet..

**Comment by fursov** [comment]
@prvakt do you know if we have an endpoint that sends event when car position changes? Currently I have one automation that is coupled to the car position, would be nice if this is pulled/informed by the server, not by periodic polling from the HA integration.

**Comment by prvakt** [comment]
@fursov I'm not aware of any MQTT endpoint which can provide position on the fly without request. I can try tomorrow to start MQTT listener before driving with my car , maybe something will show up in the logs

**Comment by WebSpider** [comment]
You might want to try if maybe subscribing to mqtt wildcard topics works.

I have not tried this myself, but maybe you can subscribe to 'any topics for my VIN'

https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/

**Comment by prvakt** [comment]
@fursov sorry it took me more than I expected but I have some good news .. there is a MQTT message published to departure topic with `name=departure-status-changed` whenever I start the car or stop the car... 
```
Message (service-event) received for TMBXXXXXXXXXXXXXX on topic departure: b'{"version":1,"traceId":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","timestamp":"2024-11-14T16:34:33Z","producer":"SKODA_MHUB","name":"departure-status-changed","data":{"userId":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","vin":"TMBXXXXXXXXXXXXXX"}}'
```
I think we can easily use this message to trigger update of specific sensor inside HA, will have a look tomorrow

**Comment by prvakt** [comment]
@fursov: position update is already implemented in myskoda 0.12.0 and for HA there is a PR [#289](https://github.com/skodaconnect/homeassistant-myskoda/pull/289) waiting to be approved

**Comment by fursov** [comment]
@prvakt Thanks a lot for this work! Very much appreciated!

**Comment by dvx76** [comment]
Can this be closed?

**Comment by fursov** [comment]
Yes, thanks for reminding!
