### ISSUE TITLE
Skoda Kamiq fixture

### ISSUE THREAD

**Issue by MarcoGos** [skodaconnect/myskoda#180]
I created a fixture for the Skoda Kamiq. I saw errors in the yaml file. That's why I didn't create a PR. Hopefully it can still be used.

[kamiq.yaml.zip](https://github.com/user-attachments/files/17683294/kamiq.yaml.zip)

**Comment by dvx76** [comment]
Thanks for the upload! I've opened a PR to add it in the project.
