### ISSUE TITLE
Failed to deserialize data: 'NOT_ACTIVATED' is not a valid VehicleState

### ISSUE THREAD

**Issue by 1358** [skodaconnect/myskoda#207]
There is a third state 'NOT_ACTIVATED' that can be returned as [VehicleState](https://github.com/skodaconnect/myskoda/blob/9aeea328f2d86eb74ad8cc18149d3cd5e39421f7/myskoda/models/info.py#L176)  

This state is returned for Vehicles that are in the app but not activated (yet). The app shows a button "Finish Activation" for theses entities.

Currently the initial enumeration already failes if there is a vehicle with this state returned by the API:

```Traceback (most recent call last):
  File "<string>", line 14, in __mashumaro_from_dict_json__
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'NOT_ACTIVATED' is not a valid VehicleState

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 10, in __mashumaro_from_json__
  File "<string>", line 16, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "state" of type VehicleState in GarageEntry has invalid value 'NOT_ACTIVATED'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 435, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 12, in __mashumaro_from_json__```

**Comment by WebSpider** [comment]
Thanks for this report!

We'll update the states we know, this will be fixed in the next release.

Out of curiousity: What did you do to get to this state?

**Comment by 1358** [comment]
I do not own this vehicle anymore. However even though Services were deactivated the v2-API returned valid data for several months. I quess either the Connect-Subscription expired or it was linked to a new master-account to get to this state.

**Comment by 1358** [comment]
As it might be helpful: this state shows like this in the app:
![photo_2024-11-14_13-35-18](https://github.com/user-attachments/assets/6cfde8fd-7eab-4a50-8c7c-3a5004b4b43c)
Tapping "Aktivierung beenden" opens a webview to identity.vwgroup.io/signin-service/v1/signin/[guid-token]@apps_vw-dilab_com?relayState=[guid-token-without-"-"]

**Comment by 1358** [comment]
WTF. I am able to regain master access to that vehicle. WTF!

**Comment by 1358** [comment]
![photo_2024-11-14_14-29-47](https://github.com/user-attachments/assets/c6663d28-3168-4d39-9c7f-87928169a47d)
stopped here. Seems as I have found a messed up path.
