### ISSUE TITLE
New fixture for Enyaq 85 2025 with outside temp

### ISSUE THREAD

**Issue by gschot** [skodaconnect/myskoda#266]
Here is a new fixture for an Enyaq 85 showing outside temp

[djapollo_enyaq_85_2025_outsidetemp.yaml.txt](https://github.com/user-attachments/files/18010394/djapollo_enyaq_85_2025_outsidetemp.yaml.txt)

**Comment by WebSpider** [comment]
Cool!

It has the OUTSIDE_TEMPERATURE capability as well. Looks like you had an update!

**Comment by gschot** [comment]
Hold the issue, I created a PR for it :)
