### ISSUE TITLE
Redirect to marketing consent after auth

### ISSUE THREAD

**Issue by Thor77** [skodaconnect/myskoda#277]
I encountered a problem with my Skoda ID (in germany) that required me to debug the authorization code to find the problem:
There was a redirect to marketing consent in place after login, could be reproduced by manually logging in to https://skodaid.vwgroup.io/account
The redirect location looked something like this: `https://identity.vwgroup.io/signin-service/v1/consent/marketing/[...]`
Would you accept a PR to add a special case in https://github.com/skodaconnect/myskoda/blob/ee14a3b5ba2f243794e19dfab88b8f097c5da1d4/myskoda/auth/authorization.py#L163 so a more meaningful error is returned instead of a KeyError because the Location header is missing?
This could be implemented the same way the TermsAndConditionsException is implemented.

**Comment by dvx76** [comment]
A PR would be great 👍 

See also https://github.com/skodaconnect/homeassistant-myskoda/issues/372

**Comment by Thor77** [comment]
I created #284

**Comment by WebSpider** [comment]
This has been merged and will appear in the next release. Thanks for your contribution! :partying_face:
