### ISSUE TITLE
Specification::trim_level should be declared as optional field

### ISSUE THREAD

**Issue by scoutice** [skodaconnect/myskoda#76]
**trim_level: str = field(metadata=field_options(alias="trimLevel"))**
should be replaced by
   **trim_level: str | None = field(default="", metadata=field_options(alias="trimLevel"))**

ERROR:myskoda.rest_api:Failed to load data from url /v2/garage/vehicles/VINVINVIN?connectivityGenerations=MOD1&connectivityGenerations=MOD2&connectivityGenerations=MOD3&connectivityGenerations=MOD4. Return value was '{"vin":"VINVINVINVINVINVIN","name":"Mein Enyaq","workshopModeEnabled":false,"licensePlate":"PLATE","state":"ACTIVATED","devicePlatform":"WCAR","softwareVersion":"3.0","specification":{"title":"Škoda Enyaq","manufacturingDate":"2021-04-08","model":"Enyaq","modelYear":"2021","body":"SUV","systemCode":"UNKNOWN","systemModelId":"5AZJJ2","maxChargingPowerInKW":125,"battery":{"capacityInKWh":77},"engine":{"type":"iV","powerInKW":150},"gearbox":{"type":"E1H"}},"servicePartner":{"servicePartnerId":"xxx"},"renders":[{"url":"https://iprenders.blob.core.windows.net/base5azs21200210/2Y2YFPQpW8TAD5-cRLexWrAB7HkqZiEz5n-PmprHKDiLh7U62wcV0ft94aRkFx-drAYkiRCUwxmWuHJPNMqn-19201080dayvext_side1080.png","viewPoint":"exterior_side","type":"REAL","order":0},{"url":"https://ip-modcwp.azureedge.net/modcwp5azs21200210/2Y2YFPQpW8TAD5-cRLexWrAB7HkqZiEz5n-PmprHKDiLh7U62wcV0ft94aRkFx-drAYkiRCUwxmWuHJPNMqn-1920658dayvext_side1080.png?v=638182953970000000","viewPoint":"garage_l","type":"REAL","order":1},{"url":"https://ip-modcwp.azureedge.net/modcwp5azs21200210/2Y2YFPQpW8TAD5-cRLexWrAB7HkqZiEz5n-PmprHKDiLh7U62wcV0ft94aRkFx-drAYkiRCUwxmWuHJPNMqn-700390dayvext_front1080.png?v=637859721980000000","viewPoint":"main","type":"REAL","order":2}],"compositeRenders":[{"layers":[{"url":"https://iprenders.blob.core.windows.net/base5azs21200210/2Y2YFPQpW8TAD5-cRLexWrAB7HkqZiEz5n-PmprHKDiLh7U62wcV0ft94aRkFx-drAYkiRCUwxmWuHJPNMqn-19201080dayvext_side1080.png","viewPoint":"exterior_side","type":"REAL","order":0}],"viewType":"UNMODIFIED_EXTERIOR_SIDE"},{"layers":[{"url":"https://iprenders.blob.core.windows.net/base5azs21200210/2Y2YFPQpW8TAD5-cRLexWrAB7HkqZiEz5n-PmprHKDiLh7U62wcV0ft94aRkFx-drAYkiRCUwxmWuHJPNMqn-19201080dayvext_side1080.png","viewPoint":"exterior_side","type":"REAL","order":0}],"modifications":{"adjustSpaceInPx":{"top":-317,"bottom":-193,"left":-149,"right":-111},"densityIndependentHeight":270,"flipHorizontal":false,"anchorTo":"LEFT"},"viewType":"HOME"},{"layers":[{"url":"https://iprenders.blob.core.windows.net/base5azs21200210/2Y2YFPQpW8TAD5-cRLexWrAB7HkqZiEz5n-PmprHKDiLh7U62wcV0ft94aRkFx-drAYkiRCUwxmWuHJPNMqn-19201080dayvext_side1080.png","viewPoint":"exterior_side","type":"REAL","order":0},{"url":"https://mspgwlivestorage.blob.core.windows.net/renders/cables/enyaq_5A_cable_charging_light_v1.png","viewPoint":"exterior_side","type":"REAL","order":1}],"modifications":{"adjustSpaceInPx":{"top":-317,"bottom":-193,"left":-149,"right":-111},"densityIndependentHeight":270,"flipHorizontal":true,"anchorTo":"LEFT"},"viewType":"CHARGING_LIGHT"},{"layers":[{"url":"https://iprenders.blob.core.windows.net/base5azs21200210/2Y2YFPQpW8TAD5-cRLexWrAB7HkqZiEz5n-PmprHKDiLh7U62wcV0ft94aRkFx-drAYkiRCUwxmWuHJPNMqn-19201080dayvext_side1080.png","viewPoint":"exterior_side","type":"REAL","order":0},{"url":"https://mspgwlivestorage.blob.core.windows.net/renders/cables/enyaq_5A_cable_charging_dark_v1.png","viewPoint":"exterior_side","type":"REAL","order":1}],"modifications":{"adjustSpaceInPx":{"top":-317,"bottom":-193,"left":-149,"right":-111},"densityIndependentHeight":270,"flipHorizontal":true,"anchorTo":"LEFT"},"viewType":"CHARGING_DARK"},{"layers":[{"url":"https://iprenders.blob.core.windows.net/base5azs21200210/2Y2YFPQpW8TAD5-cRLexWrAB7HkqZiEz5n-PmprHKDiLh7U62wcV0ft94aRkFx-drAYkiRCUwxmWuHJPNMqn-19201080dayvext_side1080.png","viewPoint":"exterior_side","type":"REAL","order":0},{"url":"https://mspgwlivestorage.blob.core.windows.net/renders/cables/enyaq_5A_cable_plugged_in_light_v1.png","viewPoint":"exterior_side","type":"REAL","order":1}],"modifications":{"adjustSpaceInPx":{"top":-317,"bottom":-193,"left":-149,"right":-111},"densityIndependentHeight":270,"flipHorizontal":true,"anchorTo":"LEFT"},"viewType":"PLUGGED_IN_LIGHT"},{"layers":[{"url":"https://iprenders.blob.core.windows.net/base5azs21200210/2Y2YFPQpW8TAD5-cRLexWrAB7HkqZiEz5n-PmprHKDiLh7U62wcV0ft94aRkFx-drAYkiRCUwxmWuHJPNMqn-19201080dayvext_side1080.png","viewPoint":"exterior_side","type":"REAL","order":0},{"url":"https://mspgwlivestorage.blob.core.windows.net/renders/cables/enyaq_5A_cable_plugged_in_dark_v1.png","viewPoint":"exterior_side","type":"REAL","order":1}],"modifications":{"adjustSpaceInPx":{"top":-317,"bottom":-193,"left":-149,"right":-111},"densityIndependentHeight":270,"flipHorizontal":true,"anchorTo":"LEFT"},"viewType":"PLUGGED_IN_DARK"}],"capabilities":{"capabilities":[{"id":"AUTOMATION","statuses":[]},{"id":"BATTERY_CHARGING_CARE","statuses":[]},{"id":"BATTERY_SUPPORT","statuses":[]},{"id":"CHARGING_PROFILES","statuses":[]},{"id":"CHARGING_STATIONS","statuses":["LICENSE_EXPIRED"]},{"id":"DIGICERT","statuses":["LICENSE_EXPIRED"]},{"id":"MAP_UPDATE","statuses":["LICENSE_EXPIRED"]},{"id":"MEASUREMENTS","statuses":["LICENSE_EXPIRED"]},{"id":"PARKING_INFORMATION","statuses":["LICENSE_EXPIRED"]},{"id":"PARKING_POSITION","statuses":["LICENSE_EXPIRED"]},{"id":"POI_SEARCH","statuses":["LICENSE_EXPIRED"]},{"id":"ROADSIDE_ASSISTANT","statuses":[]},{"id":"ROUTING","statuses":["LICENSE_EXPIRED"]},{"id":"STATE","statuses":["LICENSE_EXPIRED"]},{"id":"TRAFFIC_INFORMATION","statuses":["LICENSE_EXPIRED"]},{"id":"VEHICLE_HEALTH_INSPECTION","statuses":[]},{"id":"WARNING_LIGHTS","statuses":["LICENSE_EXPIRED"]},{"id":"WEB_RADIO","statuses":[]},{"id":"AIR_CONDITIONING_TIMERS","statuses":[]},{"id":"AIR_CONDITIONING_SMART_SETTINGS","statuses":[]},{"id":"POWERPASS_TARIFFS","statuses":[]},{"id":"AIR_CONDITIONING_SAVE_AND_ACTIVATE","statuses":[]},{"id":"CUBIC","statuses":[]},{"id":"ROUTE_PLANNING_5_CHARGERS","statuses":[]},{"id":"SUBSCRIPTIONS","statuses":[]},{"id":"DESTINATIONS","statuses":["LICENSE_EXPIRED"]},{"id":"CHARGING_MEB","statuses":[]},{"id":"VEHICLE_SERVICES_BACKUPS","statuses":[]},{"id":"EV_ROUTE_PLANNING","statuses":[]},{"id":"CHARGE_MODE_SELECTION","statuses":[]},{"id":"DIGICERT","statuses":["LICENSE_EXPIRED"]},{"id":"VEHICLE_HEALTH_WARNINGS","statuses":[]},{"id":"PAY_TO_PARK","statuses":["LICENSE_EXPIRED"]},{"id":"ONLINE_SPEECH_GPS","statuses":[]},{"id":"GUEST_USER_MANAGEMENT","statuses":[]},{"id":"DESTINATION_IMPORT_UPGRADABLE","statuses":[]},{"id":"SERVICE_PARTNER","statuses":[]},{"id":"WINDOW_HEATING","statuses":[]},{"id":"CHARGING","statuses":[]},{"id":"AIR_CONDITIONING","statuses":[]},{"id":"EXTENDED_CHARGING_SETTINGS","statuses":[]},{"id":"VEHICLE_WAKE_UP_TRIGGER","statuses":["LICENSE_EXPIRED"]}]}}'
Traceback (most recent call last):
  File "<string>", line 17, in __mashumaro_from_json__
  File "<string>", line 43, in __mashumaro_from_dict_json__
mashumaro.exceptions.MissingField: Field "trim_level" of type str is missing in Specification instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Entwicklung\Workspace\Github\skodaconnect_myskoda\myskoda\rest_api.py", line 41, in _make_get_request
    data = deserialize(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 19, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "specification" of type Specification in Info has invalid value {'title': 'Škoda Enyaq', 'manufacturingDate': '2021-04-08', 'model': 'Enyaq', 'modelYear': '2021', 'body': 'SUV', 'systemCode': 'UNKNOWN', 'systemModelId': '5AZJJ2', 'maxChargingPowerInKW': 125, 'battery': {'capacityInKWh': 77}, 'engine': {'type': 'iV', 'powerInKW': 150}, 'gearbox': {'type': 'E1H'}}
Traceback (most recent call last):
  File "<string>", line 17, in __mashumaro_from_json__
  File "<string>", line 43, in __mashumaro_from_dict_json__
mashumaro.exceptions.MissingField: Field "trim_level" of type str is missing in Specification instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\.p2\pool\plugins\org.python.pydev.core_12.0.0.202402010911\pysrc\pydevd.py", line 3616, in <module>
    main()
  File "C:\Users\User\.p2\pool\plugins\org.python.pydev.core_12.0.0.202402010911\pysrc\pydevd.py", line 3609, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\.p2\pool\plugins\org.python.pydev.core_12.0.0.202402010911\pysrc\pydevd.py", line 2626, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\.p2\pool\plugins\org.python.pydev.core_12.0.0.202402010911\pysrc\pydevd.py", line 2634, in _exec
    globals = pydevd_runpy.run_path(file, globals, '__main__')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\.p2\pool\plugins\org.python.pydev.core_12.0.0.202402010911\pysrc\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\.p2\pool\plugins\org.python.pydev.core_12.0.0.202402010911\pysrc\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\User\.p2\pool\plugins\org.python.pydev.core_12.0.0.202402010911\pysrc\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "D:\Entwicklung\Workspace\WallboxController_Python\src_myskoda\old\myskoda_get_all_info.py", line 131, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Entwicklung\Workspace\WallboxController_Python\src_myskoda\old\myskoda_get_all_info.py", line 42, in main
    info: Info = await myskoda.get_info(VIN)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Entwicklung\Workspace\Github\skodaconnect_myskoda\myskoda\myskoda.py", line 159, in get_info
    return await self.rest_api.get_info(vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Entwicklung\Workspace\Github\skodaconnect_myskoda\myskoda\rest_api.py", line 52, in get_info
    return await self._make_get_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Entwicklung\Workspace\Github\skodaconnect_myskoda\myskoda\rest_api.py", line 41, in _make_get_request
    data = deserialize(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by WebSpider** [comment]
This was already fixed in #52
