### ISSUE TITLE
AirConditioningState missing type "COOLING"

### ISSUE THREAD

**Issue by scoutice** [skodaconnect/myskoda#79]
Traceback (most recent call last):
  File "<string>", line 31, in __mashumaro_from_json__
  File "C:\Program Files\Python312\Lib\enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'COOLING' is not a valid AirConditioningState

AirConditioning(timers=[Timer(enabled=False, id=1, time=datetime.time(7, 30), type=<TimerMode.ONE_OFF: 'ONE_OFF'>, selected_days=[<Weekday.WEDNESDAY: 'WEDNESDAY'>]), Timer(enabled=False, id=2, time=datetime.time(19, 59), type=<TimerMode.ONE_OFF: 'ONE_OFF'>, selected_days=[<Weekday.WEDNESDAY: 'WEDNESDAY'>])], car_captured_timestamp=datetime.datetime(2024, 10, 5, 12, 21, 47, tzinfo=datetime.timezone.utc), errors=[], state=<**AirConditioningState.COOLING: 'COOLING**'>, steering_wheel_position=<Side.LEFT: 'LEFT'>, window_heating_state=WindowHeatingState(front=<OnOffState.OFF: 'OFF'>, rear=<OnOffState.OFF: 'OFF'>, unspecified='INVALID'), air_conditioning_at_unlock=False, charger_connection_state=<ConnectionState.CONNECTED: 'CONNECTED'>, charger_lock_state=<ChargerLockedState.LOCKED: 'LOCKED'>, estimated_date_time_to_reach_target_temperature=datetime.datetime(2024, 10, 5, 12, 50, 52, 251836, tzinfo=datetime.timezone.utc), heater_source=None, seat_heating_activated=SeatHeating(front_left=True, front_right=False), target_temperature=TargetTemperature(temperature_value=15.5, unit_in_car=<TemperatureUnit.CELSIUS: 'CELSIUS'>), window_heating_enabled=True)

**Comment by WebSpider** [comment]
Ack. This is an easy fix, accepting PR's until i have some time to fix it myself.

**Comment by smiitm** [comment]
Hey, i have added 'COOLING' state to the AirConditioningState enum. This would be my first ever PR, plese let me know if i am making any mistake.
